### ISSUE TITLE
Construcción de la ventana1 primera parte

### ISSUE THREAD

**Issue by Aleks11111111** [Aleks11111111/Clase9#1]
Construir la ventana1 y hacer el formulario para ingresar la información del cliente

**Comment by Alejandro-Poli** [comment]
Saludos voy a encargarme de esta funcionalidad

**Comment by Aleks11111111** [comment]
Listo, trabajo cumplido por favor revisar el nuevo issue para hacer en ventana1.py el formulario de registro del usuario
