### ISSUE TITLE
Programar el botón para buscar las preguntas de recuperación de contraseña

### ISSUE THREAD

**Issue by Aleks11111111** [Aleks11111111/Clase9#6]
Validar que ingrese el documentos del usuario al cual se le va a buscar la contraseña
Validar que el documento sea un dato tipo numérico
Crear la clase de usuario con sus 11 propiedades
Solo considerar un password
Buscar las preguntas para recuperar la contraseña

**Comment by Alejandro-Poli** [comment]
Voy a desarrollar este issue

**Comment by Aleks11111111** [comment]
Listo, quedo atento de su primer push y pull request

**Comment by Aleks11111111** [comment]
Se cierra este issue
